name: Hello World

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello, world!"
      - name: Print the current date
        run: echo "Today's date is $(date)"
      - name: List directory contents
        run: ls -la

